plugins {
    id 'java-library'
}

base {
    archivesName = 'zvcr-java'
    version = mod_version
}

repositories {
    mavenCentral()
}

dependencies {
    api "com.github.luben:zstd-jni:${zstd_jni_version}"

    testImplementation platform("org.junit:junit-bom:${junit_version}")
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

processResources {
    inputs.property 'mod_version', mod_version
    filesMatching('fabric.mod.json') {
        expand 'mod_version': mod_version
    }
}

test {
    useJUnitPlatform()
    testLogging {
        events 'failed', 'skipped'
        exceptionFormat 'full'
    }
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs << "-Xlint:deprecation"
    options.encoding = "UTF-8"
    options.release = Integer.parseInt(project.java_version)
}
